# Generated by Django 5.1.4 on 2025-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(max_length=20)),
                ('restaurant_cuisines', models.CharField(max_length=20)),
                ('restaurant_address', models.CharField(max_length=20)),
                ('restaurant_rating', models.CharField(max_length=20)),
                ('restaurant_photo', models.URLField(default='https://cwdaust.com.au/wpress/wp-content/uploads/2015/04/placeholder-restaurant.png', max_length=2000)),
            ],
        ),
    ]
