# Generated by Django 5.1.4 on 2025-01-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_photo',
            field=models.URLField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjjGS5iBKRcrJwPyPm1aXY4uy7KOHZwCj2hA&s', max_length=2000),
        ),
    ]
