# Generated by Django 5.1.4 on 2025-01-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_alter_menuitem_item_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_photo',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='item_price',
            new_name='price',
        ),
    ]
