# Generated by Django 5.1.4 on 2025-01-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_item_description_menuitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
    ]
